// Fictional KOL data for local development — no real names or data
export const sampleGraph = {
  nodes: [
    {
      openalex_id: "https://openalex.org/A0000000001",
      display_name: "Dr. Elena Vasquez",
      institution: "Westbrook University Medical Center",
      h_index: 82,
      citation_count: 34500,
      ops_score: 91.2,
      tier: "A",
      scientific_influence_score: 18.5,
      clinical_alignment_score: 17.8,
      reach_visibility_score: 18.2,
      nutrition_openness_score: 18.7,
      strategic_value_score: 18.0,
    },
    {
      openalex_id: "https://openalex.org/A0000000002",
      display_name: "Dr. Marcus Chen",
      institution: "Pacific Ridge Health Institute",
      h_index: 67,
      citation_count: 28900,
      ops_score: 85.4,
      tier: "A",
      scientific_influence_score: 16.2,
      clinical_alignment_score: 18.1,
      reach_visibility_score: 17.5,
      nutrition_openness_score: 16.8,
      strategic_value_score: 16.8,
    },
    {
      openalex_id: "https://openalex.org/A0000000003",
      display_name: "Dr. Sarah Okonkwo",
      institution: "Great Lakes Diabetes Center",
      h_index: 55,
      citation_count: 19200,
      ops_score: 76.3,
      tier: "B",
      scientific_influence_score: 14.8,
      clinical_alignment_score: 15.2,
      reach_visibility_score: 15.8,
      nutrition_openness_score: 16.0,
      strategic_value_score: 14.5,
    },
    {
      openalex_id: "https://openalex.org/A0000000004",
      display_name: "Dr. James Whitfield",
      institution: "Northshore Research Hospital",
      h_index: 48,
      citation_count: 15600,
      ops_score: 71.8,
      tier: "B",
      scientific_influence_score: 13.5,
      clinical_alignment_score: 14.9,
      reach_visibility_score: 14.2,
      nutrition_openness_score: 15.2,
      strategic_value_score: 14.0,
    },
    {
      openalex_id: "https://openalex.org/A0000000005",
      display_name: "Dr. Priya Sharma",
      institution: "Cascade Metabolic Institute",
      h_index: 44,
      citation_count: 12800,
      ops_score: 68.1,
      tier: "B",
      scientific_influence_score: 12.8,
      clinical_alignment_score: 13.5,
      reach_visibility_score: 14.8,
      nutrition_openness_score: 14.2,
      strategic_value_score: 12.8,
    },
    {
      openalex_id: "https://openalex.org/A0000000006",
      display_name: "Dr. Robert Engstrom",
      institution: "Heartland University Hospital",
      h_index: 38,
      citation_count: 9800,
      ops_score: 55.7,
      tier: "C",
      scientific_influence_score: 10.5,
      clinical_alignment_score: 11.2,
      reach_visibility_score: 12.0,
      nutrition_openness_score: 12.0,
      strategic_value_score: 10.0,
    },
    {
      openalex_id: "https://openalex.org/A0000000007",
      display_name: "Dr. Michelle Torres",
      institution: "Riverside Endocrine Clinic",
      h_index: 33,
      citation_count: 7500,
      ops_score: 52.4,
      tier: "C",
      scientific_influence_score: 9.8,
      clinical_alignment_score: 10.6,
      reach_visibility_score: 11.5,
      nutrition_openness_score: 10.5,
      strategic_value_score: 10.0,
    },
    {
      openalex_id: "https://openalex.org/A0000000008",
      display_name: "Dr. Alan Park",
      institution: "Summit Clinical Research",
      h_index: 29,
      citation_count: 5200,
      ops_score: 47.2,
      tier: "C",
      scientific_influence_score: 8.2,
      clinical_alignment_score: 9.5,
      reach_visibility_score: 10.5,
      nutrition_openness_score: 10.0,
      strategic_value_score: 9.0,
    },
    {
      openalex_id: "https://openalex.org/A0000000009",
      display_name: "Dr. Karen Liu",
      institution: "Eastside Medical College",
      h_index: 21,
      citation_count: 3100,
      ops_score: 38.5,
      tier: "D",
      scientific_influence_score: 6.5,
      clinical_alignment_score: 8.0,
      reach_visibility_score: 8.5,
      nutrition_openness_score: 8.5,
      strategic_value_score: 7.0,
    },
    {
      openalex_id: "https://openalex.org/A0000000010",
      display_name: "Dr. David Nakamura",
      institution: "Bayview Nutrition Lab",
      h_index: 15,
      citation_count: 1800,
      ops_score: 33.1,
      tier: "D",
      scientific_influence_score: 5.0,
      clinical_alignment_score: 7.2,
      reach_visibility_score: 6.8,
      nutrition_openness_score: 7.1,
      strategic_value_score: 7.0,
    },
  ],
  edges: [
    { source: "https://openalex.org/A0000000001", target: "https://openalex.org/A0000000002", weight: 5 },
    { source: "https://openalex.org/A0000000001", target: "https://openalex.org/A0000000003", weight: 3 },
    { source: "https://openalex.org/A0000000002", target: "https://openalex.org/A0000000004", weight: 2 },
    { source: "https://openalex.org/A0000000002", target: "https://openalex.org/A0000000005", weight: 4 },
    { source: "https://openalex.org/A0000000003", target: "https://openalex.org/A0000000006", weight: 1 },
    { source: "https://openalex.org/A0000000003", target: "https://openalex.org/A0000000004", weight: 2 },
    { source: "https://openalex.org/A0000000004", target: "https://openalex.org/A0000000007", weight: 3 },
    { source: "https://openalex.org/A0000000005", target: "https://openalex.org/A0000000006", weight: 1 },
    { source: "https://openalex.org/A0000000005", target: "https://openalex.org/A0000000008", weight: 2 },
    { source: "https://openalex.org/A0000000006", target: "https://openalex.org/A0000000009", weight: 1 },
    { source: "https://openalex.org/A0000000007", target: "https://openalex.org/A0000000008", weight: 2 },
    { source: "https://openalex.org/A0000000008", target: "https://openalex.org/A0000000010", weight: 1 },
    { source: "https://openalex.org/A0000000001", target: "https://openalex.org/A0000000005", weight: 2 },
    { source: "https://openalex.org/A0000000002", target: "https://openalex.org/A0000000003", weight: 1 },
    { source: "https://openalex.org/A0000000009", target: "https://openalex.org/A0000000010", weight: 1 },
  ],
};

export const sampleProfiles = [
  {
    _meta: { openalex_id: "https://openalex.org/A0000000001", display_name: "Dr. Elena Vasquez", ops_score: 91.2, tier: "A" },
    summary: "Leading T2D researcher at Westbrook with extensive work in dietary interventions for metabolic syndrome. Highly cited and frequently invited to ADA panels.",
    nutrition_stance_assessment: { level: "HIGH", reasoning: "Multiple publications on carbohydrate restriction and metabolic outcomes." },
    outreach_angle: "Reference her 2024 paper on ketogenic diet adherence in T2D populations — propose a data-sharing collaboration.",
    sme_briefing: "Tier A KOL with strong nutrition-first alignment. Published 3 papers on low-carb interventions last year. Ideal for advisory board consideration.",
    key_papers: [
      { title: "Ketogenic dietary patterns and glycemic control in T2D", relevance: "Directly studies the platform's core intervention approach." },
      { title: "Metabolic benefits of carbohydrate restriction", relevance: "Provides clinical evidence supporting nutrition-first T2D reversal." },
      { title: "Patient adherence in dietary interventions", relevance: "Addresses the key operational challenge in dietary T2D management." },
    ],
    red_flags: [],
  },
  {
    _meta: { openalex_id: "https://openalex.org/A0000000002", display_name: "Dr. Marcus Chen", ops_score: 85.4, tier: "A" },
    summary: "Obesity and metabolic health researcher with focus on insulin resistance pathways. Strong publication record in top endocrinology journals.",
    nutrition_stance_assessment: { level: "MEDIUM", reasoning: "Publishes on both pharmacological and dietary approaches, open to nutrition data." },
    outreach_angle: "His insulin resistance work aligns with the platform outcomes data — offer to share de-identified clinical results.",
    sme_briefing: "Tier A obesity researcher, balanced pharma/nutrition perspective. Good candidate for scientific exchange meeting. No conflicts detected.",
    key_papers: [
      { title: "Insulin sensitivity and dietary composition", relevance: "Research questions overlap with the platform's mechanism of action." },
      { title: "Comparative effectiveness of metabolic interventions", relevance: "Framework could include nutrition-first approaches." },
      { title: "Long-term outcomes in obesity management", relevance: "Addresses sustainability question central to the platform's value proposition." },
    ],
    red_flags: [],
  },
];
